"""
pipeline/config.py
==================
PipelineConfig — single source of truth for every tunable constant.

NOTE: You do NOT edit this file to tune the pipeline.
      Open run_stage2.py instead — every knob here is exposed
      in the User Control Panel at the top of that file.
"""

from dataclasses import dataclass


@dataclass
class PipelineConfig:
    """All tunable knobs for the adaptive recommendation pipeline.

    Deployment usage
    ----------------
    Default: promotion OFF, personalization dominates.
    To enable promotion set enable_promotion=True and lower
    promo_threshold_percentile (e.g. 70 = top-30% strategic score).
    All other defaults are safe starting points — override per-deployment
    by mutating the cfg object created in run_stage2_semantic_inference().
    """

    # ── Batch / output ────────────────────────────────────────────────────
    batch_size: int = 32    # users processed per GPU batch
    n_recs: int     = 10    # recommendations returned per user

    # ── Candidate gate ────────────────────────────────────────────────────
    relevance_percentile: int = 10   # drop bottom X%; keep top (100-X)%
    candidate_limit: int      = None # None = evaluate entire eligible catalog after percentile gate

    # ── Promotion label ───────────────────────────────────────────────────
    enable_promotion: bool          = False  # False → no rec ever labeled "promotion"
    promo_threshold_percentile: int = 93     # top (100-X)% strategic score qualifies

    # ── Personalization label ─────────────────────────────────────────────
    perso_label_percentile: int       = 80   # Only top 20% of items are "Personalization"
    curation_discovery_percentile: int = 60  # Only top 40% of AI scores are "Curation"
    perso_min_threshold: float        = 0.20 # Absolute floor to prevent "best of the worst" labels
    perso_match_multiplier: float     = 1.5  # amplifier in get_personalization_match
    past_items_window: int            = 10   # recent items kept in user profile

    # ── Business Quotas (set dynamically via business_goals) ──────────────
    perso_quota: int    = 7
    curation_quota: int = 2
    promo_quota: int    = 1

    top_themes: int        = 5    # top-N themes stored per user
    recency_decay: float   = 0.1  # 0 = flat history; higher = more recency weight

    # ── Scoring Weights ───────────────────────────────────────────────────
    # Format: (Curation, Strategic, Personalization, Popularity)
    cold_start_cutoff: float = 5.0   # avg_inter below → cold tier
    moderate_cutoff: float   = 20.0  # avg_inter below → moderate tier

    # 1. New Users: Curation-heavy (65% Discovery)
    cold_weights: tuple     = (0.65, 0.10, 0.15, 0.10)

    # 2. Returning Users: Balanced (50% Personalization)
    moderate_weights: tuple = (0.30, 0.10, 0.50, 0.10)

    # 3. Power Users: Personalization-heavy (70% Personalization)
    dense_weights: tuple    = (0.15, 0.10, 0.70, 0.05)

    # ── Thompson Sampling (replaces hardcoded exposure cap) ───────────────
    # Controls the explore/exploit balance of the Beta distribution sampler.
    # Higher value → more weight on AI/popularity signal → less randomness.
    # Lower value  → wider Beta curves → more exploration (good for sparse data).
    thompson_alpha_scale: float  = 50.0

    # Campaign items retain a hard ceiling (they are explicitly pushed by ops).
    cold_start_min_users: int    = 50    # skip campaign cap below this user count
    campaign_exposure_cap: float = 0.60  # promoted/clearance items capped at 60%

    # ── Discovery jitter (cold-start users) ──────────────────────────────
    discovery_jitter_threshold: float = 0.05  # trigger if max_perso < threshold

    # ── Theme diversity cap ───────────────────────────────────────────────
    per_theme_cap: int = 2  # max items from same primary theme per user

    # ── Theme clustering ──────────────────────────────────────────────────
    clustering_model: str               = 'all-MiniLM-L6-v2'
    k_min: int                          = 5
    k_max: int                          = 50
    secondary_cluster_threshold: float  = 0.85
    clustering_random_state: int        = 42
    clustering_n_init: int              = 5
    silhouette_sample_size: int         = 2000

    # ── Model paths ───────────────────────────────────────────────────────
    base_model_name: str  = "DeepFM"
    config_filename: str  = "ranking_config.yaml"
    mapping_filename: str = "rec_config.json"
    
    # ── Retrieval settings ────────────────────────────────────────────────
    retrieval_model_name: str = "LightGCN"
    retrieval_config_filename: str = "retrieval_config.yaml"
    retrieval_top_k: int | None = None  # None = Automatically retrieve 100% of the catalog
